### ISSUE TITLE
Bug in insert_or_replace_doc() function

### ISSUE THREAD

**Issue by chrisfalter** [dimitargnikolov/book-project#1]
The function includes the following lines:

```
	mongodb = MongoClient()
	db = mongodb.projectA

```
However, the correct DB is projectB. Code should read as follows:

```
	mongodb = MongoClient()
	db = mongodb.projectB

```

**Comment by dimitargnikolov** [comment]
Thanks for reporting, it's fixed now. You can do 

$ cd ~/Projects/book-project
$ git pull

to update the code if you didn't do this already.
